# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9625af876b708ee2d93d4a73cb4d6888c59734bc8326a8dbcf4471f392251d5dabf0f50b1e525cdb3465acd3617cbec4f334ae95a50e7f7aef39163c41d2f5a

test:
  secret_key_base: 73a873df0a23ced333a98f08a694b08a7d1084d1a71cfa52d25ba92d6d16de9b21fa6c040044074ba0d75682717dcb560a7b003181c5f6d5431f423d3a1011d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
